[package]
name = "socks5-server"
version = "1.2.3"
authors = ["vinoca <vinoca@vinoca.org>"]
edition = "2024"

[dependencies]
anyhow = "1.0.100"
socks5 = { package = "socks5-server", git = "https://github.com/vincascm/socks5.git" }
tokio = { version = "1", features = ["rt-multi-thread", "net", "io-util"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
